//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaHome_Frontend.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUserDTO", Namespace="http://schemas.datacontract.org/2004/07/NovaHome_Backend")]
    [System.SerializableAttribute()]
    public partial class SystemUserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoleDTO", Namespace="http://schemas.datacontract.org/2004/07/NovaHome_Backend")]
    [System.SerializableAttribute()]
    public partial class UserRoleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int roleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int roleId {
            get {
                return this.roleIdField;
            }
            set {
                if ((this.roleIdField.Equals(value) != true)) {
                    this.roleIdField = value;
                    this.RaisePropertyChanged("roleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isReg", ReplyAction="http://tempuri.org/IService1/isRegResponse")]
        string isReg(NovaHome_Frontend.ServiceReference1.SystemUserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isReg", ReplyAction="http://tempuri.org/IService1/isRegResponse")]
        System.Threading.Tasks.Task<string> isRegAsync(NovaHome_Frontend.ServiceReference1.SystemUserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isLoggedIn", ReplyAction="http://tempuri.org/IService1/isLoggedInResponse")]
        NovaHome_Frontend.ServiceReference1.UserRoleDTO isLoggedIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isLoggedIn", ReplyAction="http://tempuri.org/IService1/isLoggedInResponse")]
        System.Threading.Tasks.Task<NovaHome_Frontend.ServiceReference1.UserRoleDTO> isLoggedInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        NovaHome_Frontend.ServiceReference1.SystemUserDTO getUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        System.Threading.Tasks.Task<NovaHome_Frontend.ServiceReference1.SystemUserDTO> getUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRole", ReplyAction="http://tempuri.org/IService1/getRoleResponse")]
        string getRole(int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRole", ReplyAction="http://tempuri.org/IService1/getRoleResponse")]
        System.Threading.Tasks.Task<string> getRoleAsync(int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUserRole", ReplyAction="http://tempuri.org/IService1/setUserRoleResponse")]
        bool setUserRole(int userId, int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUserRole", ReplyAction="http://tempuri.org/IService1/setUserRoleResponse")]
        System.Threading.Tasks.Task<bool> setUserRoleAsync(int userId, int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/resetPassword", ReplyAction="http://tempuri.org/IService1/resetPasswordResponse")]
        bool resetPassword(int userId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/resetPassword", ReplyAction="http://tempuri.org/IService1/resetPasswordResponse")]
        System.Threading.Tasks.Task<bool> resetPasswordAsync(int userId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editUser", ReplyAction="http://tempuri.org/IService1/editUserResponse")]
        bool editUser(int userId, string fName, string lName, string email, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editUser", ReplyAction="http://tempuri.org/IService1/editUserResponse")]
        System.Threading.Tasks.Task<bool> editUserAsync(int userId, string fName, string lName, string email, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteUser", ReplyAction="http://tempuri.org/IService1/deleteUserResponse")]
        bool deleteUser(int userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteUser", ReplyAction="http://tempuri.org/IService1/deleteUserResponse")]
        System.Threading.Tasks.Task<bool> deleteUserAsync(int userId, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NovaHome_Frontend.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NovaHome_Frontend.ServiceReference1.IService1>, NovaHome_Frontend.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string isReg(NovaHome_Frontend.ServiceReference1.SystemUserDTO user) {
            return base.Channel.isReg(user);
        }
        
        public System.Threading.Tasks.Task<string> isRegAsync(NovaHome_Frontend.ServiceReference1.SystemUserDTO user) {
            return base.Channel.isRegAsync(user);
        }
        
        public NovaHome_Frontend.ServiceReference1.UserRoleDTO isLoggedIn(string email, string password) {
            return base.Channel.isLoggedIn(email, password);
        }
        
        public System.Threading.Tasks.Task<NovaHome_Frontend.ServiceReference1.UserRoleDTO> isLoggedInAsync(string email, string password) {
            return base.Channel.isLoggedInAsync(email, password);
        }
        
        public NovaHome_Frontend.ServiceReference1.SystemUserDTO getUser(int userId) {
            return base.Channel.getUser(userId);
        }
        
        public System.Threading.Tasks.Task<NovaHome_Frontend.ServiceReference1.SystemUserDTO> getUserAsync(int userId) {
            return base.Channel.getUserAsync(userId);
        }
        
        public string getRole(int roleId) {
            return base.Channel.getRole(roleId);
        }
        
        public System.Threading.Tasks.Task<string> getRoleAsync(int roleId) {
            return base.Channel.getRoleAsync(roleId);
        }
        
        public bool setUserRole(int userId, int roleId) {
            return base.Channel.setUserRole(userId, roleId);
        }
        
        public System.Threading.Tasks.Task<bool> setUserRoleAsync(int userId, int roleId) {
            return base.Channel.setUserRoleAsync(userId, roleId);
        }
        
        public bool resetPassword(int userId, string newPassword) {
            return base.Channel.resetPassword(userId, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> resetPasswordAsync(int userId, string newPassword) {
            return base.Channel.resetPasswordAsync(userId, newPassword);
        }
        
        public bool editUser(int userId, string fName, string lName, string email, string phone) {
            return base.Channel.editUser(userId, fName, lName, email, phone);
        }
        
        public System.Threading.Tasks.Task<bool> editUserAsync(int userId, string fName, string lName, string email, string phone) {
            return base.Channel.editUserAsync(userId, fName, lName, email, phone);
        }
        
        public bool deleteUser(int userId, string password) {
            return base.Channel.deleteUser(userId, password);
        }
        
        public System.Threading.Tasks.Task<bool> deleteUserAsync(int userId, string password) {
            return base.Channel.deleteUserAsync(userId, password);
        }
    }
}
